apiVersion: v1
kind: PersistentVolume
metadata:
  name: notejam-pv
  labels: 
    name: my-pv
spec: 
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  storageClassName: slow
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
