apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notejam-pvc
spec:
  resources: 
    requests: 
      storage: 2Gi
  storageClassName: slow
  volumeMode: Filesystem
  selector: 
    matchLabels:
      name: my-pv
  accessModes: 
    - ReadWriteOnce
